apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-dw
  name: grpc-dw
spec:
  type: ClusterIP  # Standardwert, macht den Service nur innerhalb des Clusters erreichbar
  ports:
    - name: grpc
      port: 5005        # Service-Port
      targetPort: 5005  # Port des Containers
  selector:
    service: grpc-dw  # Muss mit den Labels des Deployments übereinstimmen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-dw
  name: grpc-dw
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc-dw
  template:
    metadata:
      labels:
        service: grpc-dw
    spec:
      containers:
      - image: kklaus1616/grpc-dw:latest
        name: grpc-dw
        imagePullPolicy: Always
        ports:
          - containerPort: 5005  # Wichtig, um sicherzustellen, dass der Container den Port öffnet
      restartPolicy: Always
