apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-dw
  name: grpc-dw
spec:
  ports:
  - name: "5000"
    port: 5005
    targetPort: 5005
  selector:
    service: grpc-dw
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-dw
  name: grpc-dw
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc-dw
  template:
    metadata:
      labels:
        service: grpc-dw
    spec:
      containers:
      - image: kklaus1616/grpc-dw:latest
        name: grpc-dw
        imagePullPolicy: Always
      restartPolicy: Always
