apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-test-producer
  name: kafka-test-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-test-producer
  template:
    metadata:
      labels:
        service: kafka-test-producer
    spec:
      containers:
      - image: kklaus1616/kafka-test-producer:latest
        name: kafka-test-producer
        imagePullPolicy: Always
      restartPolicy: Always
